version: '3.8'
services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:api-dev
  api-dev:
    env_file:
      - .env
    build:
      context: ../../backend
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
    container_name: api
    ports:
      - ${PORT}:${PORT}
    environment:
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_MODEL=${AZURE_OPENAI_MODEL}
      - OPENAI_API_VERSION=${OPENAI_API_VERSION}
      - POLYGON_API_KEY=${POLYGON_API_KEY}
      - POLYGON_API_ENDPOINT=${POLYGON_API_ENDPOINT}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - PORT=${PORT}
      - APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING}
