name: Build, Test and Deploy to Azure
on: [push]
permissions:
  id-token: write

jobs:
  development:
    environment: DEVELOPMENT
    runs-on: ubuntu-latest
    steps:
    - name: Azure CLI Login
      uses: Azure/login@v2.2.0
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Azure CLI script
      uses: Azure/cli@v2.1.0
      with:
        azcliversion: latest
        inlineScript: |
          az account show

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        registry: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
        username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USER }}
        password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

    - name: Build the Docker Images
      run: |
        TAG=${{ github.sha }} docker-compose build

    - name: Push the API Image to the Container Registry
      run: |
        docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/langchain-financial-reporting-api:${{ github.sha }} 
      

